version: '3'
services:
  nest-openshift:
    image: nestjs-openshift-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
